### ISSUE TITLE
cv key_points

### ISSUE THREAD

**Issue by sssssshf** [datawhalechina/whale-anno#4]
请问如何使用这个标注工具，离线可以使用吗  ？

**Comment by Skypow2012** [comment]
可以离线使用的
1、按【快速开始】里的步骤，在自己电脑上启动项目打开页面
2、创建项目，选好类别，然后把需要标注的 .jpg/.png 打成 zip 包上传，之后就可以开始标注了，想添加图片就继续去项目编辑页里上传
3、下载标注，标注一部分后可在标注页面左下角下载 .json 格式的标注结果
